development:
  secret_key_base: 2db98790816093d4d4cc917c9c29455a068fbf74438675c4fce76edeabdbbc3b257151fd06c35ac8258be18870ab8aa019ec0f9b3c3c176985e2762a37d35e17

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

